
name: Build Client

on:
  push:
    branches: [ "master", "Dev", "QA" ]
  pull_request:
    branches: [ "master", "Dev", "QA" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: echo "installing dependencies..."
    - name: Build client app
      run: echo "building client app..."
