name: CI Pipeline

on:
  push:
    branches:
      - Dev
      - master
      - QA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build command
        run: echo "testing and building app"
